<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUy07atn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUy07atn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUy07atn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUy07atn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUy07atn\appProdProjectContainer([
    'container.build_hash' => 'Uy07atn',
    'container.build_id' => 'ff539817',
    'container.build_time' => 1641984964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUy07atn');
